import { Providers } from '@/context';
import { ButtonStyled, Navbar } from '@core/ui/components';
import type { Metadata, Viewport } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { Logoimg } from '@core/ui/assets';

const manrope = Manrope({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-manrope',
});

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	themeColor: '#7c3aed',
};

export const metadata: Metadata = {
	title: 'Boilerplate Next JS',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body
				className={`${manrope.className} font-semibold text-foreground-900`}
			>
				<Navbar title='NextJS Project' />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
