import type { Metadata, Viewport } from 'next';
import { Providers } from '../context';

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	themeColor: '#7c3aed',
};

export const metadata: Metadata = {
	title: 'Boilerplate Next JS',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
